"""empty message

Revision ID: 8394ae60d907
Revises: 
Create Date: 2017-04-22 23:46:24.337138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8394ae60d907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VoteLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('count', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('press', sa.String(length=64), nullable=True),
    sa.Column('users', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('VoteId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['VoteId'], ['VoteLog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Record')
    op.drop_table('VoteLog')
    # ### end Alembic commands ###
